import { Equipment } from './types';

export const EQUIPMENT_DATA: Equipment[] = [
  {
    id: '1',
    name: 'Roçadeira Profissional FS 160',
    category: 'roçadeira',
    brand: 'Stihl',
    power: '1.4 kW / 1.9 cv',
    pricePerDay: 85.00,
    imageUrl: 'https://picsum.photos/seed/stihl-fs160-brushcutter/600/400',
    description: 'Ideal para trabalhos intensos em gramados altos e vegetação densa. Alta performance e durabilidade.',
    available: true,
  },
  {
    id: '2',
    name: 'Cortador de Grama a Gasolina LC 140P',
    category: 'cortador',
    brand: 'Husqvarna',
    power: '1.9 kW',
    pricePerDay: 120.00,
    imageUrl: 'https://picsum.photos/seed/husqvarna-lc140p-mower/600/400',
    description: 'Fácil de usar, ideal para jardins residenciais de médio porte. Coletor de grama incluso.',
    available: true,
  },
  {
    id: '3',
    name: 'Motosserra MS 170',
    category: 'motosserra',
    brand: 'Stihl',
    power: '1.3 kW / 1.8 cv',
    pricePerDay: 75.00,
    imageUrl: 'https://picsum.photos/seed/stihl-ms170-chainsaw/600/400',
    description: 'Leve e compacta, perfeita para corte de lenha e pequenas podas em árvores.',
    available: true,
  },
  {
    id: '4',
    name: 'Soprador de Folhas BG 50',
    category: 'soprador',
    brand: 'Stihl',
    power: '0.7 kW',
    pricePerDay: 55.00,
    imageUrl: 'https://picsum.photos/seed/stihl-bg50-blower/600/400',
    description: 'Limpeza rápida e eficiente de áreas externas. Excelente relação peso/potência.',
    available: true,
  },
  {
    id: '5',
    name: 'Roçadeira Lateral a Bateria DUR181Z',
    category: 'roçadeira',
    brand: 'Makita',
    power: '18V',
    pricePerDay: 65.00,
    imageUrl: 'https://picsum.photos/seed/makita-dur181z-trimmer/600/400',
    description: 'Silenciosa e sem emissão de gases. Ideal para áreas residenciais e horários restritos.',
    available: true,
  },
  {
    id: '6',
    name: 'Cortador de Grama Dirigível (Tratorito)',
    category: 'cortador',
    brand: 'Husqvarna',
    power: '12.5 hp',
    pricePerDay: 350.00,
    imageUrl: 'https://picsum.photos/seed/husqvarna-riding-mower/600/400',
    description: 'Para grandes áreas e chácaras. Conforto e produtividade máxima no corte de grama.',
    available: true,
  },
];
